[2025-09-16T21:32:24.502+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-16T21:32:24.695+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-16T21:31:14.749783+00:00 [queued]>
[2025-09-16T21:32:24.714+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-16T21:31:14.749783+00:00 [queued]>
[2025-09-16T21:32:24.715+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-16T21:32:24.750+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): produce_entities_and_events> on 2025-09-16 21:31:14.749783+00:00
[2025-09-16T21:32:24.766+0000] {standard_task_runner.py:57} INFO - Started process 8373 to run task
[2025-09-16T21:32:24.790+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_events_minutely', 'produce_entities_and_events', 'scheduled__2025-09-16T21:31:14.749783+00:00', '--job-id', '906', '--raw', '--subdir', 'DAGS_FOLDER/generator_dag.py', '--cfg-path', '/tmp/tmp7rsux91h']
[2025-09-16T21:32:24.804+0000] {standard_task_runner.py:85} INFO - Job 906: Subtask produce_entities_and_events
[2025-09-16T21:32:24.895+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-16T21:32:25.049+0000] {task_command.py:410} INFO - Running <TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-16T21:31:14.749783+00:00 [running]> on host d6e2a7c8b3ee
[2025-09-16T21:32:25.108+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-16T21:32:25.419+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_events_minutely' AIRFLOW_CTX_TASK_ID='produce_entities_and_events' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T21:31:14.749783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T21:31:14.749783+00:00'
[2025-09-16T21:32:25.457+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.3', 29092)]>: connecting to kafka:29092 [('172.23.0.3', 29092) IPv4]
[2025-09-16T21:32:25.627+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.3', 29092)]>: Broker version identified as 2.6
[2025-09-16T21:32:25.629+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.3', 29092)]>: Connection complete.
[2025-09-16T21:32:27.407+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.23.0.3', 29092)]>: connecting to kafka:29092 [('172.23.0.3', 29092) IPv4]
[2025-09-16T21:32:27.409+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.3', 29092)]>: Connection complete.
[2025-09-16T21:32:27.409+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.3', 29092)]>: Closing connection. 
[2025-09-16T21:32:30.276+0000] {kafka.py:629} INFO - <KafkaProducer client_id=kafka-python-producer-1 transactional_id=None>: Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-09-16T21:32:30.277+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.3', 29092)]>: Closing connection. 
[2025-09-16T21:32:30.279+0000] {generator_dag.py:34} INFO - Produced 5 messages to Kafka
[2025-09-16T21:32:30.280+0000] {python.py:183} INFO - Done. Returned value was: 5
[2025-09-16T21:32:30.355+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=generate_events_minutely, task_id=produce_entities_and_events, execution_date=20250916T213114, start_date=20250916T213224, end_date=20250916T213230
[2025-09-16T21:32:30.357+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-09-16T21:32:30.803+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-16T21:32:30.843+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
