[2025-09-14T20:17:08.314+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-14T20:17:08.454+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-14T20:16:06.230197+00:00 [queued]>
[2025-09-14T20:17:08.469+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-14T20:16:06.230197+00:00 [queued]>
[2025-09-14T20:17:08.470+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-14T20:17:08.496+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): produce_entities_and_events> on 2025-09-14 20:16:06.230197+00:00
[2025-09-14T20:17:08.514+0000] {standard_task_runner.py:57} INFO - Started process 15503 to run task
[2025-09-14T20:17:08.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_events_minutely', 'produce_entities_and_events', 'scheduled__2025-09-14T20:16:06.230197+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/generator_dag.py', '--cfg-path', '/tmp/tmpyjvn3ikf']
[2025-09-14T20:17:08.527+0000] {standard_task_runner.py:85} INFO - Job 372: Subtask produce_entities_and_events
[2025-09-14T20:17:08.587+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-14T20:17:08.692+0000] {task_command.py:410} INFO - Running <TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-14T20:16:06.230197+00:00 [running]> on host 3deaa5b4a23c
[2025-09-14T20:17:08.724+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-14T20:17:08.888+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_events_minutely' AIRFLOW_CTX_TASK_ID='produce_entities_and_events' AIRFLOW_CTX_EXECUTION_DATE='2025-09-14T20:16:06.230197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-14T20:16:06.230197+00:00'
[2025-09-14T20:17:08.902+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.2', 29092)]>: connecting to kafka:29092 [('172.23.0.2', 29092) IPv4]
[2025-09-14T20:17:08.926+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.2', 29092)]>: Broker version identified as 2.6
[2025-09-14T20:17:08.929+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Connection complete.
[2025-09-14T20:17:09.778+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.23.0.2', 29092)]>: connecting to kafka:29092 [('172.23.0.2', 29092) IPv4]
[2025-09-14T20:17:09.779+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Connection complete.
[2025-09-14T20:17:09.779+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Closing connection. 
[2025-09-14T20:17:11.676+0000] {kafka.py:629} INFO - <KafkaProducer client_id=kafka-python-producer-1 transactional_id=None>: Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-09-14T20:17:11.677+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Closing connection. 
[2025-09-14T20:17:11.678+0000] {generator_dag.py:34} INFO - Produced 7 messages to Kafka
[2025-09-14T20:17:11.679+0000] {python.py:183} INFO - Done. Returned value was: 7
[2025-09-14T20:17:11.775+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=generate_events_minutely, task_id=produce_entities_and_events, execution_date=20250914T201606, start_date=20250914T201708, end_date=20250914T201711
[2025-09-14T20:17:11.777+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-09-14T20:17:12.114+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-14T20:17:12.153+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
