[2025-09-11T12:59:46.860+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-11T12:59:47.027+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_to_dds.load_users scheduled__2025-09-11T11:59:17.039170+00:00 [queued]>
[2025-09-11T12:59:47.047+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_to_dds.load_users scheduled__2025-09-11T11:59:17.039170+00:00 [queued]>
[2025-09-11T12:59:47.048+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-11T12:59:47.080+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_users> on 2025-09-11 11:59:17.039170+00:00
[2025-09-11T12:59:47.104+0000] {standard_task_runner.py:57} INFO - Started process 193 to run task
[2025-09-11T12:59:47.198+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'raw_to_dds', 'load_users', 'scheduled__2025-09-11T11:59:17.039170+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/dags_utils.py', '--cfg-path', '/tmp/tmprjwrdn3m']
[2025-09-11T12:59:47.223+0000] {standard_task_runner.py:85} INFO - Job 123: Subtask load_users
[2025-09-11T12:59:47.378+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-11T12:59:47.600+0000] {task_command.py:410} INFO - Running <TaskInstance: raw_to_dds.load_users scheduled__2025-09-11T11:59:17.039170+00:00 [running]> on host c905ba028b15
[2025-09-11T12:59:47.802+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-11T12:59:48.471+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_to_dds' AIRFLOW_CTX_TASK_ID='load_users' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T11:59:17.039170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T11:59:17.039170+00:00'
[2025-09-11T12:59:48.484+0000] {sql.py:265} INFO - Executing: 
        INSERT INTO dds.users (user_id)
        SELECT DISTINCT user_id
        FROM raw.events
        WHERE user_id IS NOT NULL
        ON CONFLICT (user_id) DO NOTHING;
        
[2025-09-11T12:59:48.575+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-11T12:59:50.270+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-11T12:59:50.297+0000] {sql.py:375} INFO - Running statement: 
        INSERT INTO dds.users (user_id)
        SELECT DISTINCT user_id
        FROM raw.events
        WHERE user_id IS NOT NULL
        ON CONFLICT (user_id) DO NOTHING;
        , parameters: None
[2025-09-11T12:59:50.304+0000] {sql.py:384} INFO - Rows affected: 0
[2025-09-11T12:59:50.344+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=raw_to_dds, task_id=load_users, execution_date=20250911T115917, start_date=20250911T125947, end_date=20250911T125950
[2025-09-11T12:59:50.393+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-11T12:59:50.499+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
